name: CI

on:
  push:
  pull_request:
  schedule:
    # Weekly Thursday 5AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 5 * * 4'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: Set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b  # v5.3.0
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install docutils flake8 pytest pytest-cov --upgrade
    - name: Tests
      run: |
        flake8 *.py --count
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@015f24e6818733317a2da2edd6290ab26238649a  # v5.0.7
      with:
        files: ./coverage.xml
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
