name: CI

on:
  push:
  pull_request:
  schedule:
    # Weekly Thursday 5AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 5 * * 4'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
    - name: Set up Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v5.4.0
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install docutils flake8 pytest pytest-cov --upgrade
    - name: Tests
      run: |
        flake8 *.py --count
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3  # v5.3.1
      with:
        files: ./coverage.xml
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}
