name: CI

on:
  push:
  pull_request:
  schedule:
    # Weekly Thursday 5AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 5 * * 4'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871  # v4.2.1
    - name: Set up Python
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install docutils flake8 pytest pytest-cov --upgrade
    - name: Tests
      run: |
        flake8 *.py --count
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238  # v4.6.0
      with:
        files: ./coverage.xml
        verbose: true
